# This workflow builds and pushes a Docker image to GHCR when a semver tag is pushed.

name: Docker Release Publish

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on semantic version tags (e.g., v1.0.0)

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true # Ensure buildx is installed

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Use the owner of the repository for login
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }} # Use the full repository name (Govcraft/svg2png)
          tags: |
            # Create tags based on the semver git tag
            type=semver,pattern={{version}} # e.g., v1.2.3 -> 1.2.3
            type=semver,pattern={{major}}.{{minor}} # e.g., v1.2.3 -> 1.2
            type=semver,pattern={{major}} # e.g., v1.2.3 -> 1
            # Add 'latest' tag only for semver tags
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable GitHub Actions cache for Docker layers
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # platforms: linux/amd64 # Uncomment and add platforms if needed